### ISSUE TITLE
드론 조종 자격증(4급) 취득하기

### ISSUE THREAD

**Issue by YunSeok-Kang** [kookmin-sw/capstone-2023-26#4]

**Comment by YunSeok-Kang** [comment]
[강윤석_무인동력비행장치 4종(무인멀티콥터).pdf](https://github.com/kookmin-sw/capstone-2023-26/files/10938247/_.4.pdf)

**Comment by hacho08** [comment]
[조현아_무인동력비행장치 4종(무인멀티콥터).pdf](https://github.com/kookmin-sw/capstone-2023-26/files/10938348/_.4.pdf)

**Comment by junghyeon0427** [comment]
[서정현_무인동력비행장치 4종(무인멀티콥터).pdf](https://github.com/kookmin-sw/capstone-2023-26/files/10938442/_.4.pdf)

**Comment by soyekwon** [comment]
[무인멀티콥터 자격증(권소예).pdf](https://github.com/kookmin-sw/capstone-2023-26/files/10938719/default.pdf)

**Comment by mjun4138** [comment]
[박민준_무인동력비행장치 4종(무인 멀티콥터).pdf](https://github.com/kookmin-sw/capstone-2023-26/files/10938764/_.4.pdf)
