### ISSUE TITLE
특정 각도에서 Face Recognition이 효과적으로 동작하는지 확인

### ISSUE THREAD

**Issue by junghyeon0427** [kookmin-sw/capstone-2023-26#5]

**Comment by hacho08** [comment]
Face Recognition 관련 git

- Recognize faces in live video using your webcam - Faster Version 사용 가능 (특정 각도에서 사용여부는 확인 필요)

https://github.com/ageitgey/face_recognition

단점: 어린아이의 얼굴은 잘 잡아내지 못한다고 함 (학습을 시킨다면 가능할 것 같음)

**Comment by hacho08** [comment]
얼굴 각도에 대한 문제는 카메라 거리 및 각도 조정

- 우리 드론에서 카메라 위치 및 각도 조정이 가능할지가 관건
- 생각보다 거리가 벌어지면서 보여지게되는 얼굴 각도가 많이 달라져서 크게 문제가 안될 것 같다는 생각이 들기도 함
- 
![KakaoTalk_Photo_2023-03-07-20-03-07.jpeg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/f71789e9-0e44-4119-a030-40601bb269dd/KakaoTalk_Photo_2023-03-07-20-03-07.jpeg)

**Comment by hacho08** [comment]
프로젝트 주제 변경으로 인해 face recognition 사용 안함
